Invoicing/Invoicing/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('clients/', include('clients.urls')),
    path('docs/', include('docs.urls')),
    path('stock/', include('stocks.urls')),
    path('reminder/', include('reminders.urls')),
    path('dash/', include('dashboard.urls')),

]

Invoicing/docs/urls.py
from django.contrib import admin
from django.urls import path, include
from docs.view.invoices.views import * 
from docs.view.quotes.views import *
from .views import *




app_name = "docs"


urlpatterns = [
    path("list/",  home, name="home"),

    ################################## Invoices URLs ##################################
    path("createIn/",  CreateInvoice.as_view(), name="createInvoice"),
    path("detailsIn/<int:pk>",  InvoiceDetailsView.as_view(), name="detailsInvoice"), # view detail of a specific invoice
    #path("deleteIn/<int:pk>",  InvoiceDeleteView.as_view(), name="deleteInvoice"), # delete a specific invoice
    path("saveInv/<int:pk>",saveInvoice, name="saveInv"),
    #path("updateIn/<int:pk>",  InvoiceUpdateView.as_view(), name="updateInvoice"), # update a specific invoice
    path("duplicate/<int:pk>",  dupInvoice, name="duplicateInvoice"), # update a specific invoice
    path("fin/<int:pk>",  finaliseInv, name="finaliseInvoice"), # finalise selected invoice
    path("unpaid_list/",  unpaidList, name="unpaidList"), # finalise selected invoice
    path("payments/<int:pk>",  payments, name="payInvoice"), # finalise selected invoice

    ################################## TRough PRoducts invoice URLs ##################################
    path('createIn/client/select/', selectClient, name='selectClient'),
    path("createIn/addprodInv/",  addPfromInv, name="addProds"), # AddProducts directly to the stock 
    path("createIn/selectprodInv/",  selecProd, name="selectProds"), # AddProducts to a selected invoice
    path("createIn/deleteArtInv/<int:pk>",  deleteArtFromInv, name="deleteArtInv"), # Delete a specific product
    path("createIn/addClientInv/",  addClientInv, name="addClientInv"), # Delete a specific product
    
    
    
    ################################## Quotes URLs ##################################
    
    path("createQt/",  CreateQuote.as_view(), name="createQuote"),
    path("detailsQt/<int:pk>",  QuoteDetailsView.as_view(), name="detailsQuote"), # view detail of a specific quote
    
    path("saveQt/<int:pk>",saveQuote, name="saveQuote"),
  
    path("duplicateQt/<int:pk>",  dupQuote, name="duplicateQuote"), # update a specific quote
    path("finQt/<int:pk>",  finaliseQuote, name="finaliseQuote"), # finalise selected quote
    path("transfer/<int:pk>",  transferToInvoice, name="transferToInvoice"), # finalise selected quote
    

    ################################## TRough PRoducts Quotes URLs ##################################
    path('createQt/client/select/', selectClientQuote, name='selectClient'),
    path("createQt/addprodQt/",  addPfromQuote, name="addProds"), # AddProducts directly to the stock 
    path("createQt/selectprodQt/",  selecProdQuote, name="selectProds"), # AddProducts to a selected quote
    path("createQt/deleteArtQt/<int:pk>",  deleteArtFromQuote, name="deleteArtQuote"), # Delete a specific product
    path("createQt/addClientQt/",  addClientQuote, name="addClientQuote"), # Delete a specific product
]

Invoicing/docs/view/credit_notes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.http import HttpResponse, JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from docs.models import *
from django.views import View
from django.contrib import messages
from docs.forms import *
from django.contrib.auth.decorators import login_required
############################ In logics imports ##############################
from datetime import date
from docs.inv_funcs import *
############################Clients CRUDs##############################################
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
############################OUTSIDES IMPORTS##############################################
from clients.forms import *
from clients.models import *
from stocks.models import *
from stocks.forms import ProdForm, ServForm



############################### INVOICES VIEWS ###############################
class CreateInvoice(View):
    """
    Create and show New Invoice lists for a specific user
    """
    #form_class = InvoiceForm
    initial = {'key': 'value'}
    template_name = 'docs/invoices/cruds/create.html'
    

    def get(self, request, *args, **kwargs):
        invoice = Invoices.objects.filter(creator=request.user).order_by('-id')[:1]
        context = {}
        
        if invoice:            
            if invoice[0].client == None:  
                artInv = Article_Inv.objects.filter(invoice=invoice[0])#Select Invoice's articles
                context = {
            
                #'logo': logo,
                'invoice': invoice[0],
                'artInv': artInv,
                }
            else:               
                creationInv(request)
                #logo = invoices[0]# Get the logo if exist
                context = {
                    #'logo': logo,
                    'invoice': invoice,
                }
        else:          
            invoices = Invoices.objects.create(dateCreation=date.today(),
                creator = request.user)
            invoice = Invoices.objects.filter(creator=request.user).order_by('-id')[:1]#select the last invoice
            
            Invoices.objects.filter(pk=invoice).update(prov_numb=firstInvoiceNumber(),
            back_status ='In Process', number=1)#Update Infos of the selected invoice
            
            invoice = invoices
            #logo = invoices[0]# Get the logo if exist
            context = {
                #'logo': logo,
                'invoice': invoice,
                'pk': invoice.pk,
            }
        return render(request, self.template_name, context)

#############################################################################
########################### Begin AJAXING INVOICE ###########################
#############################################################################

#-----------------------------Articles----------------------------#
def addPfromInv(request,  *args, **kwargs):
    '''
    This view is made to make a direct new article from the 
    invoice template
    '''
    data = dict()
    invoice = Invoices.objects.filter(creator=request.user).order_by('-id')[:1]

    if request.method == 'POST':
        form1 = ProdForm(request.POST)
        form2 = ServForm(request.POST)
        if form1.is_valid():
            sell = request.POST.get("sellPrice")
            buy = request.POST.get("buyPrice")
            if buy == None:
                buy = 0
            elif sell == None:
                sell = 0
            clt = form1.save(commit=False)           
            clt.owner = request.user
            clt.gainMargin = Decimal(sell) - Decimal(buy)
            clt.articleType = 'prod'          
            clt.save()
            data["form_is_valid"] = True          
        elif form2.is_valid():
            clt = form2.save(commit=False)              
            clt.owner = request.user
            clt.articleType = 'srv'
            clt.save()   
            data["form_is_valid"] = True
        else:
            data['form_is_valid'] = False
    else:
        form1 = ProdForm()
        form2 = ServForm()
    context = {'form1': form1,
    'form2':form2}
    data["html_form"] = render_to_string('docs/invoices/ajax/new_article.html',
        context,
        request=request,
    )
    return JsonResponse(data)

def selecProd(request,  *args, **kwargs):
    '''
    This view is made to add a direct article to the 
    invoice and refresh the template
    '''
    data = dict()
    invoice = Invoices.objects.filter(creator=request.user).order_by('-id')[:1]
    artInv = Article_Inv.objects.filter(invoice=invoice[0])#Select Invoice's articles
    invc = invoice[0]
    if request.method == 'POST':
        form = AddArticlesForm(request.user, request.POST)
        if form.is_valid():
            clt = form.save(commit=False)
            articlePrice = Article.objects.filter(pk=clt.article.pk)
            clt.amount = (articlePrice[0].sellPrice * clt.qte)-clt.remise
            clt.invoice = invoice[0]            
            Invoices.objects.filter(creator=request.user).update(
                sub_total= subTotal(clt, invoice[0]),
                tax_one= taxConversionInvI(invc, clt.amount, clt.tax_one),
                tax_two= taxConversionInvII(invc, clt.amount, clt.tax_two),   
            )
                       
            Invoices.objects.filter(creator=request.user).update(
                   total = total(invc, subTotal(clt, invc))         
            )
            form.save()
            invoice = Invoices.objects.filter(creator=request.user).order_by('-id')[:1]

            data['form_is_valid'] = True
            data['html_select_article'] = render_to_string('docs/invoices/ajax/partial-articles-list.html', {
                'artInv': artInv
            })
            data['html_total_dynamic'] = render_to_string('docs/invoices/ajax/partial-total-updates.html', {
                'invoice': invoice[0]
            })
        else:
            data['form_is_valid'] = False
    else:
        form = AddArticlesForm(request.user)

    context = {'form': form,
    'artInv': artInv}
    data['html_form'] = render_to_string('docs/invoices/ajax/artInv.html',
        context,

        request=request
    )
    return JsonResponse(data)

def deleteArtFromInv(request, pk, *args, **kwargs):

    '''
    This view is for deleting a specific article from 
    a specific Invoice
    '''
    article = get_object_or_404(Article_Inv, pk=pk)
    data = dict()
    invoice = Invoices.objects.filter(creator=request.user).order_by('-id')[:1]
    invc = invoice[0]
    if request.method == 'POST':
        Invoices.objects.filter(creator=request.user).update(
                sub_total= subTotal_(article, invc),
                tax_one= taxConversionInv_I(invc, article.amount, article.tax_one),
                tax_two= taxConversionInv_II(invc, article.amount, article.tax_two),   
            )
            
            
        Invoices.objects.filter(creator=request.user).update(
                total = total_(invc, article)         
        )
        article.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        artInv =  Article_Inv.objects.filter(invoice=invoice[0])
        data['html_select_article'] = render_to_string('docs/invoices/ajax/partial-articles-list.html', {
            'artInv': artInv
        })
        data['html_total_dynamic'] = render_to_string('docs/invoices/ajax/partial-total-updates.html', {
                'invoice': invoice[0]
            })
    else:
        context = {'article': article}
        data['html_form'] = render_to_string('docs/invoices/ajax/partial-article-delete.html',
            context,
            request=request,
        )
    return JsonResponse(data)

#-----------------------------Clients----------------------------#
def selectClient(request, *args, **kwargs):
    """
    This view is for ajax select and show client infos
    """
    data = dict()
    invoice = Invoices.objects.filter(creator=request.user).order_by('-id')[:1]
    if request.method == "POST":
        IdClient = request.POST.get("client")
        if IdClient:
            client = Clients.objects.filter(pk=IdClient)
            Invoices.objects.filter(pk=invoice).update(client= client[0],deadlinePay=client[0].payments_conditions)

            data['form_is_valid'] = True

            data['html_select_client'] = render_to_string('docs/invoices/ajax/client-partial-select.html', {
            'client':client[0],
            })
       
    else:
        clients = Clients.objects.filter(createdBy=request.user, actif=True)
        context = {'clients': clients}
        data['html_form'] = render_to_string('docs/invoices/ajax/select_client.html',
            context,
            request=request,
        )


    return JsonResponse(data)


def addClientInv(request,  *args, **kwargs):
    '''
    This view is made to make a direct new client from the 
    invoice template
    '''
    data = dict()
    print('IM HERE YEAH')

    if request.method == 'POST':
        form = ClientForm(request.POST)
       
        if form.is_valid():
            clt = form.save(commit=False)
            clt.actif = True
            clt.createdBy = request.user
            clt.save()
            data["form_is_valid"] = True
            
        
        
    else:
        

        form = ClientForm()
        
    context = {'form': form,
   }
    data["html_form"] = render_to_string('docs/invoices/ajax/partial-new-client.html',
        context,
        request=request,
    )
    return JsonResponse(data)

#-----------------------------INVOICE's OPEARATIONS----------------------------#

###########################################################################

Invoicing/docs/views.py
from django.shortcuts import render
from .models import *
# Create your views here.



def home(request):
    invoices = Invoices.objects.filter(creator=request.user)
    quotes = Quotes.objects.filter(creator=request.user)
    context={
        "invoices": invoices,
        "quotes": quotes,
    }

    return render(request, 'docs/lists.html', context)

Invoicing/docs/templates/docs/credits_notes/ajax/artCN.html
{% load static %}
<div id="accordionWrapa1" role="tablist" aria-multiselectable="true">
    <div class="modal-header">

        <h4 class="modal-title">Select a new Article</h4>
    </div>
    <div class="modal-body">

        <div class="card" style="min-height: 200px;">

            <div class="card-content collapse show">
                <div class="card-body">
                    <form method="post" action="{% url 'docs:selectProds' %}" class=" form js-select-article-form">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <div class="form-actions">

                            <button type="submit" class="btn btn-primary">
                                <i class="la la-check-square-o"></i> Add
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn mb-1 btn-secondary btn-lg btn-block" data-dismiss="modal"><i
                class="ft-x"></i>Close</button>
    </div>

</div>

<script src="{% static '/app-assets/vendors/js/vendors.min.js' %}"></script>

<script src="{% static '/app-assets/js/core/app.js' %}"></script>
<script src="{% static '/app-assets/data/locales/en.json' %}"></script>

Invoicing/docs/templates/docs/credits_notes/ajax/client-partial-select.html
<ul class="px-0 list-unstyled">
    <li class="text-bold-800">{{ client.firstName}}</li>
    <li class="text-bold-800">{{ client.name}}</li>
    <li class="text-bold-800">{{ client.companyName}}</li>
    <li class="text-bold-800">{{ client.adresse}}</li>
    <li class="text-bold-800">{{ client.email}}</li>
</ul>

Invoicing/docs/templates/docs/credits_notes/ajax/new_article.html
{% load static %}
<div id="accordionWrapa1" role="tablist" aria-multiselectable="true">
    <div class="modal-header">

        <h4 class="modal-title">Create a new Article</h4>
    </div>
    <div class="modal-body">


        <div class="card accordion">
            <a id="heading1" class="card-header collapsed" role="tab" data-toggle="collapse" href="#accordion1"
                aria-expanded="false" aria-controls="accordion1">
                <div class="card-title lead">+ Add new Product</div>
            </a>
            <div id="accordion1" role="tabpanel" data-parent="#accordionWrapa1" aria-labelledby="heading1"
                class="collapse">
                <div class="card-content">
                    <div class="card-body">
                        <form method="post" action="{% url 'docs:addProds' %}" class="js-article-create-form">
                            {% csrf_token %}

                            <div class="form-group{% if field.errors %} has-error{% endif %}">
                                <label for="{{ field.id_for_label }}">{{ form1.as_p }}</label>

                            </div>



                            <button type="submit" class="btn btn-primary">Add Product</button>
                        </form>
                    </div>
                </div>
            </div>
            <a id="heading2" class="card-header collapsed" data-toggle="collapse" href="#accordion2"
                aria-expanded="false" aria-controls="accordion2">
                <div class="card-title lead collapsed">+ Create New Service</div>
            </a>
            <div id="accordion2" role="tabpanel" data-parent="#accordionWrapa1" aria-labelledby="heading2"
                class="collapse" aria-expanded="false">
                <div class="card-content">
                    <div class="card-body">
                        <form method="post" action="{% url 'docs:addProds' %}" class="js-article-create-form">
                            {% csrf_token %}

                            <div class=" form-group{% if field.errors %} has-error{% endif %}">
                                <label for="{{ field.id_for_label }}">{{ form2.as_p }}</label>

                            </div>



                            <button type="submit" class="btn btn-primary">Add Service</button>
                        </form>
                    </div>
                </div>
            </div>


        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn mb-1 btn-secondary btn-lg btn-block" data-dismiss="modal"><i
                class="ft-x"></i>Close</button>
    </div>

</div>

<script src="{% static '/app-assets/vendors/js/vendors.min.js' %}"></script>

<script src="{% static '/app-assets/js/core/app.js' %}"></script>
<script src="{% static '/app-assets/data/locales/en.json' %}"></script>

Invoicing/docs/templates/docs/credits_notes/ajax/partial-article-delete.html
{% load static %}
<form method="post" action="{% url 'docs:deleteArtInv' article.pk %}" class="js-article-delete-form">
    {% csrf_token %}
    <div class="modal-header">

            <h4 class="modal-title">Confirm article deletion</h4> 

        
    </div>
    <div class="modal-body">
        <p class="lead">Are you sure you want to delete the article, <strong>{{ article.article.name }}</strong>?</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-danger">Delete Article</button>
    </div>
</form>

Invoicing/docs/templates/docs/credits_notes/ajax/partial-articles-list.html
{% for article in artInv %}
<tr>
    <th scope="row">
        {{ article.article.ref }}
    </th>

    <td class="text-right">{{ article.article.name }}</td>
    <td class="text-right">{{ article.article.type }}</td>
    <td class="text-right">{{ article.article.unit }}</td>
    <td class="text-right">{{ article.qte }}</td>
    <td class="text-right">{{ article.article.sellPrice }}</td>
    <td class="text-right">{{ article.tax_one }}%</td>
    <td class="text-right">{{ article.tax_two }}%</td>
    <td class="text-right">{{ article.amount}}</td>

    <td><button type="button" class="btn btn-danger btn-sm js-delete-article"
            data-url="{% url 'docs:deleteArtInv' article.pk %}">
            <i class="fas fa-trash"></i>Delete
        </button></td>

</tr>
{% empty %}
<tr>
    <td class="text-center">----No Articles Yet!----</td>
</tr>
{% endfor %}

Invoicing/docs/templates/docs/credits_notes/ajax/partial-new-client.html
{% load static %}
<form method="post" action="{% url 'docs:addClientInv' %}" class=".js-client-new-form">
    {% csrf_token %}
    <div class="modal-header">

        <h4 class="modal-title">create new Client</h4>
    </div>
    <div class="modal-body">

        <div class="form-group">
           
            
                {{ form.as_p }}


        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary"> Done</button>
    </div>

</form>

Invoicing/docs/templates/docs/credits_notes/ajax/partial-save-invoice.html
{% load static %}
{% csrf_token %}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Invoice Number : {{ invoice.pk }}</h4>
</div>
<div class="modal-body">
    <p class="lead">invoice number: <strong>{{ invoice.pk }}</strong> <strong style='clor:green;'>Have ben well
            Saved</strong>
    </p>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

</div>

Invoicing/docs/templates/docs/credits_notes/ajax/partial-total-updates.html
<tr>
    <td>Sub Total</td>
    <td class="text-right"> 
    
    $ {{ invoice.sub_total }}
    
    

       </td>
</tr>
<tr>
    <td>TAX 1</td>
    <td class="text-right"> 
        $ {{ invoice.tax_one }}
        </td>
</tr>
<tr>
    <td>TAX 2</td>
    <td class="text-right">
        $ {{ invoice.tax_two }}
        </td>
</tr>
<tr>
    <td class="text-bold-800">Total</td>
    <td class="text-bold-800 text-right"> 
        $ {{ invoice.total }}
        </td>
</tr>

Invoicing/docs/templates/docs/credits_notes/ajax/select_client.html
{% load static %}

<form method="post" action="{% url 'docs:selectClient' %}" class=".js-client-select-form">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Select a Client</h4>
    </div>
    <div class="modal-body">

        <div class="form-group{% if client.errors %} has-error{% endif %}">
            <label for="{{ field.id_for_label }}">{{ client.name }}</label>
            <select id="issueinput5" name="client" class="form-control" data-toggle="tooltip" data-trigger="hover"
                data-placement="top" data-title="Priority" data-original-title="" title="">
                {% for client in clients %}

                <option value="{{client.pk}}">{{client.name}}</option>
                {% endfor %}

            </select>

        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary"> Done</button>
    </div>

</form>