Invoicing/Invoicing/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('clients/', include('clients.urls')),
    path('docs/', include('docs.urls')),
    path('stock/', include('stocks.urls')),
    path('reminder/', include('reminders.urls')),
    path('dash/', include('dashboard.urls')),

]

Invoicing/docs/urls.py
from django.contrib import admin
from django.urls import path, include
from docs.view.invoices.views import * 
from docs.view.quotes.views import *
from .views import *




app_name = "docs"


urlpatterns = [
    path("list/",  home, name="home"),

    ################################## Invoices URLs ##################################
    path("createIn/",  CreateInvoice.as_view(), name="createInvoice"),
    path("detailsIn/<int:pk>",  InvoiceDetailsView.as_view(), name="detailsInvoice"), # view detail of a specific invoice
    #path("deleteIn/<int:pk>",  InvoiceDeleteView.as_view(), name="deleteInvoice"), # delete a specific invoice
    path("saveInv/<int:pk>",saveInvoice, name="saveInv"),
    #path("updateIn/<int:pk>",  InvoiceUpdateView.as_view(), name="updateInvoice"), # update a specific invoice
    path("duplicate/<int:pk>",  dupInvoice, name="duplicateInvoice"), # update a specific invoice
    path("fin/<int:pk>",  finaliseInv, name="finaliseInvoice"), # finalise selected invoice
    path("unpaid_list/",  unpaidList, name="unpaidList"), # finalise selected invoice
    path("payments/<int:pk>",  payments, name="payInvoice"), # finalise selected invoice

    ################################## TRough PRoducts invoice URLs ##################################
    path('createIn/client/select/', selectClient, name='selectClient'),
    path("createIn/addprodInv/",  addPfromInv, name="addProds"), # AddProducts directly to the stock 
    path("createIn/selectprodInv/",  selecProd, name="selectProds"), # AddProducts to a selected invoice
    path("createIn/deleteArtInv/<int:pk>",  deleteArtFromInv, name="deleteArtInv"), # Delete a specific product
    path("createIn/addClientInv/",  addClientInv, name="addClientInv"), # Delete a specific product
    
    
    
    ################################## Quotes URLs ##################################
    
    path("createQt/",  CreateQuote.as_view(), name="createQuote"),
    path("detailsQt/<int:pk>",  QuoteDetailsView.as_view(), name="detailsQuote"), # view detail of a specific quote
    
    path("saveQt/<int:pk>",saveQuote, name="saveQuote"),
  
    path("duplicateQt/<int:pk>",  dupQuote, name="duplicateQuote"), # update a specific quote
    path("finQt/<int:pk>",  finaliseQuote, name="finaliseQuote"), # finalise selected quote
    path("transfer/<int:pk>",  transferToInvoice, name="transferToInvoice"), # finalise selected quote
    

    ################################## TRough PRoducts Quotes URLs ##################################
    path('createQt/client/select/', selectClientQuote, name='selectClient'),
    path("createQt/addprodQt/",  addPfromQuote, name="addProds"), # AddProducts directly to the stock 
    path("createQt/selectprodQt/",  selecProdQuote, name="selectProds"), # AddProducts to a selected quote
    path("createQt/deleteArtQt/<int:pk>",  deleteArtFromQuote, name="deleteArtQuote"), # Delete a specific product
    path("createQt/addClientQt/",  addClientQuote, name="addClientQuote"), # Delete a specific product
]

Invoicing/docs/view/credit_notes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.http import HttpResponse, JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from docs.models import *
from django.views import View
from django.contrib import messages
from docs.forms import *
from django.contrib.auth.decorators import login_required
############################ In logics imports ##############################
from datetime import date
from docs.inv_funcs import *
############################Clients CRUDs##############################################
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
############################OUTSIDES IMPORTS##############################################
from clients.forms import *
from clients.models import *
from stocks.models import *
from stocks.forms import ProdForm, ServForm



############################### INVOICES VIEWS ###############################
class CreateInvoice(View):
    """
    Create and show New Invoice lists for a specific user
    """
    #form_class = InvoiceForm
    initial = {'key': 'value'}
    template_name = 'docs/invoices/cruds/create.html'
    

    def get(self, request, *args, **kwargs):
        invoice = Invoices.objects.filter(creator=request.user).order_by('-id')[:1]
        context = {}
        
        if invoice:            
            if invoice[0].client == None:  
                artInv = Article_Inv.objects.filter(invoice=invoice[0])#Select Invoice's articles
                context = {
            
                #'logo': logo,
                'invoice': invoice[0],
                'artInv': artInv,
                }
            else:               
                creationInv(request)
                #logo = invoices[0]# Get the logo if exist
                context = {
                    #'logo': logo,
                    'invoice': invoice,
                }
        else:          
            invoices = Invoices.objects.create(dateCreation=date.today(),
                creator = request.user)
            invoice = Invoices.objects.filter(creator=request.user).order_by('-id')[:1]#select the last invoice
            
            Invoices.objects.filter(pk=invoice).update(prov_numb=firstInvoiceNumber(),
            back_status ='In Process', number=1)#Update Infos of the selected invoice
            
            invoice = invoices
            #logo = invoices[0]# Get the logo if exist
            context = {
                #'logo': logo,
                'invoice': invoice,
                'pk': invoice.pk,
            }
        return render(request, self.template_name, context)

#############################################################################
########################### Begin AJAXING INVOICE ###########################
#############################################################################

#-----------------------------Articles----------------------------#
def addPfromInv(request,  *args, **kwargs):
    '''
    This view is made to make a direct new article from the 
    invoice template
    '''
    data = dict()
    invoice = Invoices.objects.filter(creator=request.user).order_by('-id')[:1]

    if request.method == 'POST':
        form1 = ProdForm(request.POST)
        form2 = ServForm(request.POST)
        if form1.is_valid():
            sell = request.POST.get("sellPrice")
            buy = request.POST.get("buyPrice")
            if buy == None:
                buy = 0
            elif sell == None:
                sell = 0
            clt = form1.save(commit=False)           
            clt.owner = request.user
            clt.gainMargin = Decimal(sell) - Decimal(buy)
            clt.articleType = 'prod'          
            clt.save()
            data["form_is_valid"] = True          
        elif form2.is_valid():
            clt = form2.save(commit=False)              
            clt.owner = request.user
            clt.articleType = 'srv'
            clt.save()   
            data["form_is_valid"] = True
        else:
            data['form_is_valid'] = False
    else:
        form1 = ProdForm()
        form2 = ServForm()
    context = {'form1': form1,
    'form2':form2}
    data["html_form"] = render_to_string('docs/invoices/ajax/new_article.html',
        context,
        request=request,
    )
    return JsonResponse(data)

def selecProd(request,  *args, **kwargs):
    '''
    This view is made to add a direct article to the 
    invoice and refresh the template
    '''
    data = dict()
    invoice = Invoices.objects.filter(creator=request.user).order_by('-id')[:1]
    artInv = Article_Inv.objects.filter(invoice=invoice[0])#Select Invoice's articles
    invc = invoice[0]
    if request.method == 'POST':
        form = AddArticlesForm(request.user, request.POST)
        if form.is_valid():
            clt = form.save(commit=False)
            articlePrice = Article.objects.filter(pk=clt.article.pk)
            clt.amount = (articlePrice[0].sellPrice * clt.qte)-clt.remise
            clt.invoice = invoice[0]            
            Invoices.objects.filter(creator=request.user).update(
                sub_total= subTotal(clt, invoice[0]),
                tax_one= taxConversionInvI(invc, clt.amount, clt.tax_one),
                tax_two= taxConversionInvII(invc, clt.amount, clt.tax_two),   
            )
                       
            Invoices.objects.filter(creator=request.user).update(
                   total = total(invc, subTotal(clt, invc))         
            )
            form.save()
            invoice = Invoices.objects.filter(creator=request.user).order_by('-id')[:1]

            data['form_is_valid'] = True
            data['html_select_article'] = render_to_string('docs/invoices/ajax/partial-articles-list.html', {
                'artInv': artInv
            })
            data['html_total_dynamic'] = render_to_string('docs/invoices/ajax/partial-total-updates.html', {
                'invoice': invoice[0]
            })
        else:
            data['form_is_valid'] = False
    else:
        form = AddArticlesForm(request.user)

    context = {'form': form,
    'artInv': artInv}
    data['html_form'] = render_to_string('docs/invoices/ajax/artInv.html',
        context,

        request=request
    )
    return JsonResponse(data)

def deleteArtFromInv(request, pk, *args, **kwargs):

    '''
    This view is for deleting a specific article from 
    a specific Invoice
    '''
    article = get_object_or_404(Article_Inv, pk=pk)
    data = dict()
    invoice = Invoices.objects.filter(creator=request.user).order_by('-id')[:1]
    invc = invoice[0]
    if request.method == 'POST':
        Invoices.objects.filter(creator=request.user).update(
                sub_total= subTotal_(article, invc),
                tax_one= taxConversionInv_I(invc, article.amount, article.tax_one),
                tax_two= taxConversionInv_II(invc, article.amount, article.tax_two),   
            )
            
            
        Invoices.objects.filter(creator=request.user).update(
                total = total_(invc, article)         
        )
        article.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        artInv =  Article_Inv.objects.filter(invoice=invoice[0])
        data['html_select_article'] = render_to_string('docs/invoices/ajax/partial-articles-list.html', {
            'artInv': artInv
        })
        data['html_total_dynamic'] = render_to_string('docs/invoices/ajax/partial-total-updates.html', {
                'invoice': invoice[0]
            })
    else:
        context = {'article': article}
        data['html_form'] = render_to_string('docs/invoices/ajax/partial-article-delete.html',
            context,
            request=request,
        )
    return JsonResponse(data)

#-----------------------------Clients----------------------------#
def selectClient(request, *args, **kwargs):
    """
    This view is for ajax select and show client infos
    """
    data = dict()
    invoice = Invoices.objects.filter(creator=request.user).order_by('-id')[:1]
    if request.method == "POST":
        IdClient = request.POST.get("client")
        if IdClient:
            client = Clients.objects.filter(pk=IdClient)
            Invoices.objects.filter(pk=invoice).update(client= client[0],deadlinePay=client[0].payments_conditions)

            data['form_is_valid'] = True

            data['html_select_client'] = render_to_string('docs/invoices/ajax/client-partial-select.html', {
            'client':client[0],
            })
       
    else:
        clients = Clients.objects.filter(createdBy=request.user, actif=True)
        context = {'clients': clients}
        data['html_form'] = render_to_string('docs/invoices/ajax/select_client.html',
            context,
            request=request,
        )


    return JsonResponse(data)


def addClientInv(request,  *args, **kwargs):
    '''
    This view is made to make a direct new client from the 
    invoice template
    '''
    data = dict()
    print('IM HERE YEAH')

    if request.method == 'POST':
        form = ClientForm(request.POST)
       
        if form.is_valid():
            clt = form.save(commit=False)
            clt.actif = True
            clt.createdBy = request.user
            clt.save()
            data["form_is_valid"] = True
            
        
        
    else:
        

        form = ClientForm()
        
    context = {'form': form,
   }
    data["html_form"] = render_to_string('docs/invoices/ajax/partial-new-client.html',
        context,
        request=request,
    )
    return JsonResponse(data)

#-----------------------------INVOICE's OPEARATIONS----------------------------#

###########################################################################

Invoicing/docs/views.py
from django.shortcuts import render
from .models import *
# Create your views here.



def home(request):
    invoices = Invoices.objects.filter(creator=request.user)
    quotes = Quotes.objects.filter(creator=request.user)
    context={
        "invoices": invoices,
        "quotes": quotes,
    }

    return render(request, 'docs/lists.html', context)

Invoicing/docs/templates/docs/lists.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1> List of Documents </h1>


<div class="card">

    <div class="card-header">
        <div class="form-group">
            <a href="{% url 'docs:createInvoice' %}" class="btn mr-1 mb-1 btn-primary">+ NEW INVOICE</a>
            <a href="{% url 'docs:createQuote' %}" class="btn mr-1 mb-1 btn-secondary">+ NEW QUOTE</a>
        </div>
        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
        <div class="heading-elements">
            <ul class="list-inline mb-0">
                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
            </ul>
        </div>
    </div>
    <div class="card-content collapse show" style="">
        <div class="card-body card-dashboard dataTables_wrapper dt-bootstrap">
            <p class="card-text">Export Your Data an multiple format :</p>
            <div id="DataTables_Table_10_wrapper" class="dataTables_wrapper dt-bootstrap4">

                <table class="table table-striped table-bordered file-export dataTable" id="DataTables_Table_10"
                    role="grid" aria-describedby="DataTables_Table_10_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_10" rowspan="1"
                                colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending"
                                style="width: 139px;">Number</th>
                            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_10" rowspan="1" colspan="1"
                                aria-label="Position: activate to sort column ascending" style="width: 228px;">Type
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_10" rowspan="1" colspan="1"
                                aria-label="Office: activate to sort column ascending" style="width: 99px;">Client</th>
                            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_10" rowspan="1" colspan="1"
                                aria-label="Age: activate to sort column ascending" style="width: 40px;">Statut</th>


                        </tr>
                    </thead>
                    <tbody>

                        {% for inv in invoices %}
                        <tr role="row" class="odd">
                            <td class="sorting_1">
                                <a href="{% url 'docs:detailsInvoice' inv.pk %}">
                                    
                                    {% if inv.fnb %}
                                    {{ inv.fnb }}
                                    {% else %}
                                    {{ inv.prov_numb }}
                                    {% endif %}                                       
                                </a>
                            </td>
                            <td>Invoice</td>
                            <td>
                            {% if inv.client %}
                            {{ inv.client.name }}    
                            {% else %}
                            ------ No Client Selected Yet ------
                            {% endif %}
                                 </td>
                            <td>{{ inv.stats }} - {{ inv.back_status }}</td>
                        </tr>
                        {% endfor %}
                        {% for qut in quotes %}
                        <tr role="row" class="odd">
                            <td class="sorting_1">
                                <a href="{% url 'docs:detailsQuote' qut.pk %}">
                                    
                                    {% if qut.fnb %}
                                    {{ qut.fnb }}
                                    {% else %}
                                    {{ qut.prov_numb }}
                                    {% endif %}                                       
                                </a>
                            </td>
                            <td>Quote</td>
                            <td>{% if qut.client %}
                                {{ qut.client.name }}    
                                {% else %}
                                ------ No Client Selected Yet ------
                                {% endif %}</td>
                            <td>{{ qut.stats }} - {{ qut.back_status }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <th rowspan="1" colspan="1">Number</th>
                            <th rowspan="1" colspan="1">Type</th>
                            <th rowspan="1" colspan="1">Client</th>
                            <th rowspan="1" colspan="1">Statut</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>



<!-- BEGIN: Vendor JS-->
<script src="{% static '/app-assets/vendors/js/vendors.min.js' %}"></script>
<script src="{% static '/app-assets/vendors/js/material-vendors.min.js' %}"></script>
<script src="{% static '/app-assets/vendors/js/tables/datatable/datatables.min.js' %}"></script>
<script src="{% static '/app-assets/vendors/js/tables/datatable/dataTables.buttons.min.js' %}"></script>
<script src="{% static '/app-assets/vendors/js/tables/buttons.flash.min.js' %}"></script>
<script src="{% static '/app-assets/vendors/js/tables/jszip.min.js' %}"></script>
<script src="{% static '/app-assets/vendors/js/tables/pdfmake.min.js' %}"></script>
<script src="{% static '/app-assets/vendors/js/tables/vfs_fonts.js' %}"></script>
<script src="{% static '/app-assets/vendors/js/tables/buttons.html5.min.js' %}"></script>
<script src="{% static '/app-assets/vendors/js/tables/buttons.print.min.js' %}"></script>
<!-- BEGIN Vendor JS-->
{% endblock content %}