Invoicing/Invoicing/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('clients/', include('clients.urls')),
    path('docs/', include('docs.urls')),
    path('stock/', include('stocks.urls')),
    path('reminder/', include('reminders.urls')),
    path('dash/', include('dashboard.urls')),

]

Invoicing/docs/urls.py
from django.contrib import admin
from django.urls import path, include
from docs.view.invoices.views import * 
from docs.view.quotes.views import *
from .views import *




app_name = "docs"


urlpatterns = [
    path("list/",  home, name="home"),

    ################################## Invoices URLs ##################################
    path("createIn/",  CreateInvoice.as_view(), name="createInvoice"),
    path("detailsIn/<int:pk>",  InvoiceDetailsView.as_view(), name="detailsInvoice"), # view detail of a specific invoice
    #path("deleteIn/<int:pk>",  InvoiceDeleteView.as_view(), name="deleteInvoice"), # delete a specific invoice
    path("saveInv/<int:pk>",saveInvoice, name="saveInv"),
    #path("updateIn/<int:pk>",  InvoiceUpdateView.as_view(), name="updateInvoice"), # update a specific invoice
    path("duplicate/<int:pk>",  dupInvoice, name="duplicateInvoice"), # update a specific invoice
    path("fin/<int:pk>",  finaliseInv, name="finaliseInvoice"), # finalise selected invoice
    path("unpaid_list/",  unpaidList, name="unpaidList"), # finalise selected invoice
    path("payments/<int:pk>",  payments, name="payInvoice"), # finalise selected invoice

    ################################## TRough PRoducts invoice URLs ##################################
    path('createIn/client/select/', selectClient, name='selectClient'),
    path("createIn/addprodInv/",  addPfromInv, name="addProds"), # AddProducts directly to the stock 
    path("createIn/selectprodInv/",  selecProd, name="selectProds"), # AddProducts to a selected invoice
    path("createIn/deleteArtInv/<int:pk>",  deleteArtFromInv, name="deleteArtInv"), # Delete a specific product
    path("createIn/addClientInv/",  addClientInv, name="addClientInv"), # Delete a specific product
    
    
    
    ################################## Quotes URLs ##################################
    
    path("createQt/",  CreateQuote.as_view(), name="createQuote"),
    path("detailsQt/<int:pk>",  QuoteDetailsView.as_view(), name="detailsQuote"), # view detail of a specific quote
    
    path("saveQt/<int:pk>",saveQuote, name="saveQuote"),
  
    path("duplicateQt/<int:pk>",  dupQuote, name="duplicateQuote"), # update a specific quote
    path("finQt/<int:pk>",  finaliseQuote, name="finaliseQuote"), # finalise selected quote
    path("transfer/<int:pk>",  transferToInvoice, name="transferToInvoice"), # finalise selected quote
    

    ################################## TRough PRoducts Quotes URLs ##################################
    path('createQt/client/select/', selectClientQuote, name='selectClient'),
    path("createQt/addprodQt/",  addPfromQuote, name="addProds"), # AddProducts directly to the stock 
    path("createQt/selectprodQt/",  selecProdQuote, name="selectProds"), # AddProducts to a selected quote
    path("createQt/deleteArtQt/<int:pk>",  deleteArtFromQuote, name="deleteArtQuote"), # Delete a specific product
    path("createQt/addClientQt/",  addClientQuote, name="addClientQuote"), # Delete a specific product
]

Invoicing/stocks/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *




app_name = "stocks"


urlpatterns = [
    path('home/', home, name='home'),
    path('addProd/', CreateProd.as_view(), name='createProd'),
    path('update/<int:pk>', articleUpdateView, name='updateArticle'),
    path('addServ/', CreateServ.as_view(), name='createServ'),
    path('detailProd/<int:pk>', ProdDetailsView.as_view(), name='details'),
    path("deactivate/<int:pk>",  deactivateArticle, name="deactivateArticle"),
    path('addUnit/', createUnit, name='addUnit'),

]

Invoicing/stocks/models.py
from django.db import models
from django.contrib.auth.models import User





class Units(models.Model):
    
    name = models.CharField(max_length=50, blank=False)

    def __str__(self):
        return self.name

class Tax(models.Model):
    name = models.CharField(max_length=150, blank=True)
    value = models.IntegerField(blank=True)



class Article(models.Model):

    types_to_select =[
        ('service', 'srv'),
        ('product', 'prod'),
    ]

    owner =  models.ForeignKey(User, on_delete=models.CASCADE)
    articleType = models.CharField(max_length=100,  choices=types_to_select)
    name = models.CharField(max_length=150, blank=True)
    ref = models.CharField(max_length=150, blank=True)
    unit = models.ForeignKey(Units, on_delete=models.CASCADE)
    actif = models.BooleanField(null=True, default=True)
    buyPrice = models.DecimalField(max_digits=19, decimal_places=2, blank=True, null=True)
    gainMargin = models.DecimalField(max_digits=19, decimal_places=2,  blank=True,null=True)
    sellPrice = models.DecimalField(max_digits=19, decimal_places=2,  blank=True,null=True)

    def __str__(self):
        return '{} {}'.format(self.name, self.articleType)

    

Invoicing/stocks/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import *



################################### Invoices's linkded forms ################################### 
class ProdForm(ModelForm):
    """
    Form of Products CRUDS
    """
    def __init__(self, *args, **kwargs):
        super(ProdForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control'})

    class Meta:

        model = Article
        exclude = ['owner', 'gainMargin','articleType']


class ServForm(ModelForm):
    """
    Form of Services CRUDS
    """
    def __init__(self, *args, **kwargs):
        super(ServForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control'})

    class Meta:

        model = Article
        exclude = ['owner', 'gainMargin','buyPrice','articleType']


class UnitForm(ModelForm):
    """
    Form of Units CRUDS
    """
    def __init__(self, *args, **kwargs):
        super(UnitForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control'})

    class Meta:
        model = Units
        fields = '__all__'

Invoicing/stocks/views.py
import json
from django.http import JsonResponse,  HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from .models import *
from django.urls import reverse_lazy
from django.views import View
from django.contrib import messages
from .forms import *
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string, get_template

############################ In logics imports ##############################
import datetime
from .funcs import *
from decimal import Decimal
############################Stocks CRUDs##############################################
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView




def home(request):
    articles = Article.objects.filter(owner=request.user, actif=True)
    
    context={
        'articles':articles,
    }

    return render(request, 'stocks/home.html', context)


############################### Stock's VIEWS ###############################


class CreateProd(View):
    """
    Create New Products for a specific user
    """
    
    form_class = ProdForm
    initial = {'key': 'value'}
    template_name = 'stocks/cruds/createProd.html'
    

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        context = {
            'form':form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        
        form = self.form_class(request.POST)
        context = {
            'form': form,
        }
        if form.is_valid():
            sell = request.POST.get("sellPrice")
            buy = request.POST.get("buyPrice")
            if buy == None:
                buy = 0
            elif sell == None:
                sell = 0
            clt = form.save(commit=False)
            print('-------------------------------->', request.user)
            clt.owner = request.user
            clt.gainMargin = Decimal(sell) - Decimal(buy)
            clt.articleType = 'prod'
            clt.save()
            return redirect('stocks:home')
        else:
            print('noooooooooooooo')
        return render(request, self.template_name, context=context)



class CreateServ(View):
    """
    Create  New Services for a specific user
    """
    
    form_class = ServForm
    initial = {'key': 'value'}
    template_name = 'stocks/cruds/createServ.html'
    

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        context = {
            'form':form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        
        form = self.form_class(request.POST)
        context = {
            'form': form,
        }
        if form.is_valid():
            
            clt = form.save(commit=False)
            print('-------------------------------->', request.user)
            clt.owner = request.user
            clt.articleType = 'srv'
            clt.save()
            return redirect('stocks:home')
        else:
            print('noooooooooooooo')
        return render(request, self.template_name, context=context)


class ProdDetailsView(DetailView):
    """
    showing details of an invoice
    """
    model = Article
    template_name = 'stocks/cruds/details.html'
    context_object_name = 'article'

def createUnit(request):
    '''
    This view is for Adding a new units
    '''
    data = dict()

    if request.method == 'POST':
        form = UnitForm(request.POST)
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            
            data['html_book_list'] = render_to_string('stocks/home.html', {

            })
        else:
            data['form_is_valid'] = False
    else:
        form = UnitForm()

    context = {'form': form}
    data['html_form'] = render_to_string('stocks/ajax/partial-unit-add.html',
        context,
        request=request
    )
    return JsonResponse(data)



def deactivateArticle(request, pk, *args, **kwargs):
    '''
    This view is for Deleting a specific client from 
    the Article's list
    '''
    article = get_object_or_404(Article, pk=pk)
    data = dict()
   
    if request.method == 'POST':
        data['form_is_valid'] = True  # This is just to play along with the existing code
        Article.objects.filter(pk=article.pk).update(actif=False)
        data['article'] = render_to_string('stocks/home.html', {
            'article': article,
        })
    else:
        context = {'article': article}
        data['html_form'] = render_to_string('stocks/ajax/partial-deactivate-article.html',
            context,
            request=request,
        )
    return JsonResponse(data)

def articleUpdateView(request, pk): 
    '''
    update view for articles 
    '''
    # dictionary for initial data with  
    # field names as keys 
    context ={} 
    # fetch the object related to passed id 
    obj = get_object_or_404(Article, pk = pk) 
    print('/////////////////////////////////////',obj.articleType)
    if obj.articleType == 'product' :
        form = ProdForm(request.POST or None, instance = obj) 
    else:
        form = ServForm(request.POST or None, instance = obj) 

    # save the data from the form and 
    # redirect to detail_view 
    if form.is_valid(): 
        #elt = form.save(commit=False)
        
        form.save() 
        return redirect("stocks:home") 
    else:
        
        context["form"] = form 
    # add form dictionary to context 
    context["form"] = form 
  
    return render(request, "stocks/cruds/update.html", context) 

Invoicing/stocks/templates/stocks/cruds/createProd.html
{% extends "base.html" %}


{% block content %}




<div class="card">
    <div class="card-header">
        <h1 class="form-section">New Product:</h1>

        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
        <div class="heading-elements">
            <ul class="list-inline mb-0">
                <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
            </ul>
        </div>
    </div>
    <div class="card-body">



        <div class="form-body">


            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <div>
                    <button class="btn mr-1 mb-1 btn-primary btn-lg" type="submit">Create</button>
                </div>
            </form>
        </div>

    </div>
</div>


<script>

</script>
{% endblock content %}

Invoicing/stocks/templates/stocks/cruds/createServ.html
{% extends "base.html" %}


{% block content %}




<div class="card">
    <div class="card-header">
        <h1 class="form-section">New Service:</h1>

        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
        <div class="heading-elements">
            <ul class="list-inline mb-0">
               
                <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
            </ul>
        </div>
    </div>
    <div class="card-body">



        <div class="form-body">


            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <div>
                    <button class="btn mr-1 mb-1 btn-primary btn-lg" type="submit">Create</button>
                </div>
            </form>





        </div>

    </div>
</div>


{% endblock content %}

Invoicing/stocks/templates/stocks/cruds/details.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="card">
    <div class="card-content">
        <div class="card-body">
          
            <div class="col-12">
                <h2 class="mb-1"><i class="ft-tag"></i> Article Informations 
                {% if article.actif %}
                <i class="ft-zap" style="color: green; font: muli 12px;">ACTIF</i>
                {% else %}
                <i class="ft-zap" style="color: red; font: muli 12px;">Non Actif</i>
                {% endif %}

                    </h2>
                <table class="table">
                    <tbody>
                        <tr>
                            <td><span style="font-weight: bold;">Reference :</span></td>
                            <td class="users-view-username"> {{ article.reference }}</td>
                        </tr>
                        <tr>
                            <td><span style="font-weight: bold;">Name:</span></td>
                            <td class="users-view-name"> {{ article.name }}</td>
                        </tr>
                        <tr>
                            <td><span style="font-weight: bold;">Type :</span></td>
                            <td class="users-view-email"> {{ article.articleType }}</td>
                        </tr>
                        <tr>
                            <td><span style="font-weight: bold;">Unit used :</span></td>
                            <td> {{ article.unit }}</td>
                        </tr>
                        <tr>
                            <td><span style="font-weight: bold;">Price Sell :</span></td>
                            <td> {{ article.sellPrice }}</td>
                        </tr>
                        
                        {% if article.articleTyp == 'product' or  article.articleTyp == 'prod' %}
                        <tr>
                            <td><span style="font-weight: bold;">Buy Price :</span></td>
                            <td> {{ article.buyPrice }}</td>
                        </tr>
                        <tr>
                            <td><span style="font-weight: bold;">Gain margin :</span></td>
                            <td> {{ article.gainMargin }}</td>
                        </tr>
                        {% endif %}
                            
                       
                    </tbody>
                </table>
                
               
            </div>
          
           
            
        </div>
        <div class="col-xl-4 col-lg-12 mb-1">
            <div class="form-group text-center">
                
                <a href="{% url 'stocks:home' %}" class="btn btn-float btn-blue"><i class="ft-rewind"></i><span>Go Back</span></a>
                <a href="{% url 'stocks:updateArticle' article.pk%}" class="btn btn-float btn-blue"><i class="ft-edit"></i><span>Edit</span></a>
                
                {% if article.actif %}
                <button type="button" data-url="{% url 'stocks:deactivateArticle' article.pk %}" class="btn btn-float btn-pink js-deactivate-article"><i class="ft-trash">Deactivate</i></button>
                    
                {% endif %}
                    

            </div>
        </div>
    </div>
</div>
<!-- Modal for selecting client-->
<div class="modal fadeInUp" id="modal-article">
    <div class="modal-dialog">
        <div class="modal-content">


        </div>
    </div>
</div>
<script src="{% static '/assets/js/stock/ajaxStorm.js' %}"></script>

{% endblock content%}

Invoicing/stocks/templates/stocks/cruds/update.html
{% extends "base.html" %}
{% block content %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Article Update</h5>
        {{ article.name }}
    </div>
    <div class="card-body">
        <form class="form" method="post">
            {% csrf_token %}
            <div class="form-body">
                <h4 class="form-section"><i class="ft-user"></i> Personal Info</h4>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="projectinput1">Article Name</label>
                            {{form.name}}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="projectinput2">Refrence</label>
                            {{form.ref}}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="projectinput3">Unit</label>
                            {{form.unit}}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="projectinput4">Status Actif</label>
                           {{form.actif}}
                        </div>
                    </div>
                </div>

                

                <div class="form-group">
                    <label for="companyName">Price Selling</label>
                    {{form.sellPrice}}
                </div>

                {% if article.articleType == 'product' or article.articleType == 'prod' %}
    
        
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="projectinput5">Price bought with</label>
                                {{form.buyPrice}}
                            </div>
                        </div>

                        
                    </div>

                {% endif %}


                

                
            <div class="form-actions">

                <button type="submit" class="btn btn-primary">
                    <i class="la la-check-square-o"></i> Save
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}